groups:
  enable:
  # 允许响应的群 roomId，大概长这样：2xxxxxxxxx3@chatroom，新增就加一行
  - xxx@chatroom
  - 20782264501@chatroom

administrators:
  wxid: wxid_clooze21y79721


chatgpt:
  model_name: "gpt-3.5-turbo"
  api_key: "sk-zpAHa2F4LeepcXwOzR8PASFWFbPxSRN6Cy4r31NuiNjLwpsq"
  api_key_option: [
    "sk-zpAHa2F4LeepcXwOzR8PASFWFbPxSRN6Cy4r31NuiNjLwpsq",
  ]




